// Sidebars are generated by tools/resolve.js — one per simulator (docs/sidebars-<slug>.json).
const fs = require("fs");
const path = require("path");

const docsDir = path.join(__dirname, "docs");
const sidebars = {};
if (fs.existsSync(docsDir)) {
  for (const f of fs.readdirSync(docsDir)) {
    const m = f.match(/^sidebars-(.+)\.json$/);
    if (m) sidebars[m[1]] = JSON.parse(fs.readFileSync(path.join(docsDir, f), "utf8"));
  }
}
module.exports = sidebars;
